development: &default
  adapter: postgresql
  encoding: unicode
  database: hound_development
  pool: 5
  host: localhost
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

test:
  <<: *default
  database: hound_test
